- name: restart rke2-server
  service:
    name: rke2-server
    state: restarted
  become: True
  become_user: root

- name: restart rke2-agent
  service:
    name: rke2-agent
    state: restarted
  become: True
  become_user: root
